### ISSUE TITLE
Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by haryhouqin** [patrikx3/redis-ui#10]
It pops "Cannot read property '1' of undefined" when connected.

**Comment by haryhouqin** [comment]
connect fali

**Comment by ccaballero646** [comment]
Hello!
Still seeing this issue. Can you take a look?
In TEST CONNECTION says "Redis Connected Successfully"
Log: 
```
[2019/07/17 22:02:04.926] [P3XRS] [PID: 000001]  [INFO] socket.io connection-connect P3Xidf138ae10c61010008ceef41de0ceaa lothar-cache05 connected
[2019/07/17 22:02:04.940] [P3XRS] [PID: 000001]  [WARN] socket.io getStreamKeys dbsize 3 count 100
[2019/07/17 22:02:04.953] [P3XRS] [PID: 000001]  [ERROR] TypeError: Cannot read property '1' of undefined
    at getKeysInfo (/usr/local/lib/node_modules/p3x-redis-ui/node_modules/p3x-redis-ui-server/src/service/socket.io/shared.js:236:43)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async getFullInfo (/usr/local/lib/node_modules/p3x-redis-ui/node_modules/p3x-redis-ui-server/src/service/socket.io/shared.js:275:20)
    at async Object.getFullInfoAndSendSocket (/usr/local/lib/node_modules/p3x-redis-ui/node_modules/p3x-redis-ui-server/src/service/socket.io/shared.js:298:20)
    at async generateConnectInfo (/usr/local/lib/node_modules/p3x-redis-ui/node_modules/p3x-redis-ui-server/src/service/socket.io/request/connection-connect.js:30:5)
    at async Redis.<anonymous> (/usr/local/lib/node_modules/p3x-redis-ui/node_modules/p3x-redis-ui-server/src/service/socket.io/request/connection-connect.js:169:21)
[2019/07/17 22:02:21.015] [P3XRS] [PID: 000001]  [WARN] socket.io shared disconnect redis includes true length === 1 1

```

**Comment by akdj** [comment]
Hi @p3x-robot 

I also get this error, when I try to connect to my local redis  (in docker container), I am using the v2019.10.125 version from Snap Store

**Comment by akdj** [comment]
which keys?  What I did, is open p3x redis ui, then creation new connection, test the connection, and connect to it.  I didn't a key filed during those steps :/

**Comment by akdj** [comment]
No... I cannot connect to my redis database, That's the issue...

**Comment by akdj** [comment]
It is a simple standalone redis in docker

**Comment by akdj** [comment]
Ok, will retry tomorrow, will keep you up

**Comment by akdj** [comment]
news: The UI can connect to Redis, if Redis is not dockerized
