### ISSUE TITLE
Cannot read property '1' of undefined connecting to redis 3.2.11

### ISSUE THREAD

**Issue by micdenny** [patrikx3/redis-ui#18]
Connecting to a redis node (v3.2.11) in a cluster, I get the error `Cannot read property '1' of undefined`

![image](https://user-images.githubusercontent.com/1633595/58881357-58a96600-86da-11e9-973d-bfcc9e6da505.png)

This is my server info:

```
# Server
redis_version:3.2.11
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:7f7585cc3328f16d
redis_mode:cluster
os:Linux 3.10.0-862.14.4.el7.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
gcc_version:4.8.5
process_id:953
run_id:3ce298d45e2642ef76c7b9b16efaf890436e8357
tcp_port:6381
uptime_in_seconds:9670777
uptime_in_days:111
hz:10
lru_clock:16149683
executable:/usr/local/bin/redis-server
config_file:/etc/redis/6381.conf
```

**EDIT: more details**

here's the console log took from the server version:

```
[P3XRS] 2019/06/04 15:12:07.985 [INFO]   [PID: 000203] socket.io connected p1yFiFD61Z0x9UekAAAA
[P3XRS] 2019/06/04 15:12:21.788 [WARN]   [PID: 000203] socket.p3xrs.connectionId undefined
[P3XRS] 2019/06/04 15:12:21.790 [INFO]   [PID: 000203] socket.io disconnected p1yFiFD61Z0x9UekAAAA
[P3XRS] 2019/06/04 15:12:22.076 [INFO]   [PID: 000203] socket.io connected ySV0aR3gj0An-BrlAAAB
[P3XRS] 2019/06/04 15:12:24.939 [WARN]   [PID: 000203] shared disconnectRedisIo try
[P3XRS] 2019/06/04 15:12:24.940 [INFO]   [PID: 000203] socket.io connection-connect added new socket.id ySV0aR3gj0An-BrlAAAB to P3Xid84bfc922b6101000077ad052f9b35a name with production-odcom-dmz-master-6381
[P3XRS] 2019/06/04 15:12:24.989 [INFO]   [PID: 000203] socket.io connection-connect P3Xid84bfc922b6101000077ad052f9b35a production-odcom-dmz-master-6381 connected
[P3XRS] 2019/06/04 15:12:25.063 [WARN]   [PID: 000203] socket.io getStreamKeys dbsize 10520 count 100
[P3XRS] 2019/06/04 15:12:35.568 [INFO]   [PID: 000203] socket.io connection-connect redis was already connected
[P3XRS] 2019/06/04 15:12:35.651 [WARN]   [PID: 000203] socket.io getStreamKeys dbsize 10367 count 100
[P3XRS] 2019/06/04 15:12:39.771 [ERROR]  [PID: 000203] TypeError: Cannot read property '1' of undefined
    at getKeysInfo (/usr/lib/node_modules/p3x-redis-ui/node_modules/p3x-redis-ui-server/src/service/socket.io/shared.js:222:43)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by micdenny** [comment]
> i doubt it works with Redis 3, i only test on Redis 5 and I do not support Redis Stable version below 3

ok, that could be the problem

> only with standalone, or maybe redis sentinel, but i only work on standalone.

standalone support could be enough, I can switch between nodes, or use the console to find in which node is the key I'm searching, enumerating the keys from multiple nodes could be a pain to develop, need to know the nodes, then submit the scan for each nodes, then aggregate the data, a PITA.

> pull requests are welcome

good to know 😉

**Comment by micdenny** [comment]
I've double checked my redis version between production and staging, I was expecting to have newer version on staging, but that's not true, in both environment I'm using redis `3.2.11` both in cluster, I can't understand why I get that error in production and it works fine on staging.

**Comment by micdenny** [comment]
> u use 1 web i stance right?

I use only one web tab / instance, I've also tried with the desktop app


> try deleting the connection and create a new one, and paste here you connections file.

where's the connections file in linux when starting as service as you describe in the guide (I can't find the file in the user home directory)? and where's is when running as desktop app?

**Comment by micdenny** [comment]
BTW the line is 222, not 22, this one: https://github.com/patrikx3/redis-ui-server/blob/master/src/service/socket.io/shared.js#L222

> shared.js:222:43

**Comment by micdenny** [comment]
maybe in the keys there's some type that is not supported in this piece of code?

```js
        switch(obj.type) {
            case 'hash':
                complexLengthPipeline.hlen(key)
                break;

            case 'list':
                complexLengthPipeline.llen(key)
                break;

            case 'set':
                complexLengthPipeline.scard(key)
                break;

            case 'zset':
                complexLengthPipeline.zcard(key)
                break;
        }
```

but as far as I know I'm using that redis types

**Comment by micdenny** [comment]
Unfortunately I can't do it, but I will try to replicate the same cluster in an environment where I can open ports

**Comment by micdenny** [comment]
> p3x redis ui uses ioredis, and it does not handle clusters, that is the problem

now seems to support it:

> Full-featured. It supports Cluster, Sentinel, Pipelining and of course Lua scripting & Pub/Sub (with the support of binary messages).

https://github.com/luin/ioredis

**Comment by micdenny** [comment]
I will give it a try later, I should be able to debug myself, I really want to provide an easy tool for the team to connect to a redis instance and check key values when we spot some problem and we want to dig into it, they also know how to use redis-cli, but a ui will be much more faster, to avoid scan the entire database the scan with a limit and a filter can be used, etc.. this tool you did is really good, and it's a shame that cannot work in cluster, I mean, at least connect to the cluster nodes as they were standalone should be possible, of course if you ask for a specific key that is in another node you get reply from redis that you should move, but that's ok for me

I suspect there's a problem that is not 100% related to the cluster, I will see
