### ISSUE TITLE
Does not run on Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [patrikx3/redis-ui#2]
```
AppRun.
9/21/2018, 6:00:06 PM unhandledRejection TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at basename (path.js:1395:5)
    at Command.parse (/run/firejail/appimage/.appimage-9973/resources/app.asar/node_modules/p3x-redis-ui-server/node_modules/commander/index.js:462:30)
    at cli (/run/firejail/appimage/.appimage-9973/resources/app.asar/node_modules/p3x-redis-ui-server/src/lib/cli.js:12:10)
    at boot (/run/firejail/appimage/.appimage-9973/resources/app.asar/node_modules/p3x-redis-ui-server/src/lib/boot.js:12:10)
    at Object.<anonymous> (/run/firejail/appimage/.appimage-9973/resources/app.asar/src/electron/app.js:4:1)
    at Object.<anonymous> (/run/firejail/appimage/.appimage-9973/resources/app.asar/src/electron/app.js:51:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32) Promise {
  <rejected> TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at basename (path.js:1395:5)
    at Command.parse (/run/firejail/appimage/.appimage-9973/resources/app.asar/node_modules/p3x-redis-ui-server/node_modules/commander/index.js:462:30)
    at cli (/run/firejail/appimage/.appimage-9973/resources/app.asar/node_modules/p3x-redis-ui-server/src/lib/cli.js:12:10)
    at boot (/run/firejail/appimage/.appimage-9973/resources/app.asar/node_modules/p3x-redis-ui-server/src/lib/boot.js:12:10)
    at Object.<anonymous> (/run/firejail/appimage/.appimage-9973/resources/app.asar/src/electron/app.js:4:1)
    at Object.<anonymous> (/run/firejail/appimage/.appimage-9973/resources/app.asar/src/electron/app.js:51:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32) }
Parent pid 9973, child pid 9977
```

Reference:
https://github.com/AppImage/appimage.github.io/pull/825

**Comment by probonopd** [comment]
Is it possible to compile it on Ubuntu 14.04?

**Comment by probonopd** [comment]
The point of AppImage is that everything that does not come with the system by default has to come inside the AppImage. So you need to put node inside. But a version that can run on Ubuntu 14.04.
