### ISSUE TITLE
latest docker version prints this error: PM unhandledRejection TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string.

### ISSUE THREAD

**Issue by Rastusik** [patrikx3/redis-ui#27]
Hi, I just pulled the latest docker build and I'm getting this in the docker logs:

```
10/15/2019, 12:36:20 PM unhandledRejection TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.resolve (path.js:981:7)
    at cli (/usr/local/lib/node_modules/p3x-redis-ui/node_modules/p3x-redis-ui-server/src/lib/cli.js:81:42)
    at boot (/usr/local/lib/node_modules/p3x-redis-ui/node_modules/p3x-redis-ui-server/src/lib/boot.js:12:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/p3x-redis-ui/bin/p3x-redis.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10) Promise {
  <rejected> TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
      at validateString (internal/validators.js:112:11)
      at Object.resolve (path.js:981:7)
      at cli (/usr/local/lib/node_modules/p3x-redis-ui/node_modules/p3x-redis-ui-server/src/lib/cli.js:81:42)
      at boot (/usr/local/lib/node_modules/p3x-redis-ui/node_modules/p3x-redis-ui-server/src/lib/boot.js:12:10)
      at Object.<anonymous> (/usr/local/lib/node_modules/p3x-redis-ui/bin/p3x-redis.js:3:1)
      at Module._compile (internal/modules/cjs/loader.js:945:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
      at Module.load (internal/modules/cjs/loader.js:798:32)
      at Function.Module._load (internal/modules/cjs/loader.js:711:12)
      at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10)
}
```

I'm running the redis ui from docker compose:
```
redis-ui:
        container_name: redis-ui
        image: patrikx3/p3x-redis-ui:latest
        volumes:
            - ./docker/redis-ui/:/settings:ro
        depends_on:
            - redis1
            - redis2
            - redis3
```

and the `./docker/redis-ui/` folder contains the following:
`.p3xrs-conns.json`:
```
{
    "update": "2019-09-02T13:16:22.855Z",
    "list": [
        {
            "name": "redis-cluster",
            "cluster": true,
            "nodes": [
                {
                    "host": "redis1",
                    "port": 6379
                },
                {
                    "host": "redis2",
                    "port": 6379
                },
                {
                    "host": "redis3",
                    "port": 6379
                }
            ],
            "host": "redis1",
            "port": 6379,
            "id": "P3Xid0f3a53c2a6101000079605a4c12345"
        }
    ]
}
```

It would be nice to have tagged releases, so it would be possible to revert to last stable version.

**Comment by Rastusik** [comment]
great, it's working! :) thank you very much for the fast response!
