### ISSUE TITLE
gcloud memorystore support

### ISSUE THREAD

**Issue by psarka** [patrikx3/redis-ui#31]
Hi,

I'd love to use this with the gcloud memory store, but currently it does not work, as the CLIENT command is disabled (see bottom for the full list of blocked commands https://cloud.google.com/memorystore/docs/reference/redis-configs).

An example instance of the error, is when pressing TEST CONNECTION button:

```
ERR unknown command `client`, with args beginning with: `list`, 
```

If the CLIENT command is not crucial, and there was a workaround, I'd love to know :)

Thanks!

**Comment by psarka** [comment]
Docker

**Comment by psarka** [comment]
Unfortunately I get the same error when running with `patrickx3/px-redis-ui:debug`. 

(The version string at the top left of the screen shows `v2019.10.173`, for what its worth)

![Screenshot from 2020-01-11 17-11-25](https://user-images.githubusercontent.com/1212244/72207121-da921680-3495-11ea-82b7-b6261bd8592c.png)

**Comment by psarka** [comment]
The error in the logs is as folows:

```
[ERROR] ReplyError: ERR unknown command `client`, with args beginning with: `list`, 
    at parseError (/usr/local/lib/node_modules/p3x-redis-ui/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/usr/local/lib/node_modules/p3x-redis-ui/node_modules/redis-parser/lib/parser.js:302:14)
```

**Comment by psarka** [comment]
Progress! Now the connection works, but I get an error when selecting connection in the main page. It hits another forbidden command CONFIG:

```
ERR unknown command `config`, with args beginning with: `get`, `databases`,
```

**Comment by psarka** [comment]
Ups, missed that. It works! :tada:
