### ISSUE TITLE
Unable to connect to AWS ElasticCache Instance

### ISSUE THREAD

**Issue by andyast** [patrikx3/redis-ui#46]
Getting the following error when running docker image in K8S using the manifests files.  For what's it worth "Test Connection" says successful.

Config
```json
{
      "list": [
        {
          "name": "Prod",
          "host": "master.<redacted>.cache.amazonaws.com",
          "port": 6379,
          "password": "<redacted>",
          "awsElastiCache": true
        }
      ]
}
```

Error
```
[P3XRS] [PID: 000007]  ParserError: Protocol error, got "\u0015" as reply type byte. Please report this.
    at handleError (/usr/local/lib/node_modules/p3x-redis-ui/node_modules/redis-parser/lib/parser.js:190:15)
    at parseType (/usr/local/lib/node_modules/p3x-redis-ui/node_modules/redis-parser/lib/parser.js:304:14) {
  offset: 1,
  buffer: '{"type":"Buffer","data":[21,0,0,0,2,1,0]}'
}

[P3XRS] [PID: 000007]  socket.io connection-connect added new socket.id NOa5AkPFyewyOQkvAAAB to undefined name with Prod

[P3XRS] [PID: 000007]  socket.io connection-connect undefined Prod connected
```

**Comment by andyast** [comment]
And Yes it is most likely an issue with `redis-parser` but I was wondering if anyone has successfully used AWS ElasticCache

**Comment by esdee-git** [comment]
worked for me after enabling Aws ElastiCache as pointed out in https://github.com/patrikx3/redis-ui/issues/12
