### ISSUE TITLE
Crash when adding new connection

### ISSUE THREAD

**Issue by Frontrider** [patrikx3/redis-ui#53]
I get this crash when opening settings, using docker on openshift (not using the template you provided, as it had no healthchecks):

 uncaughtException TypeError: Cannot read property 'map' of undefined
at Object.sendConnections (/usr/local/lib/node_modules/p3x-redis-ui/node_modules/p3x-redis-ui-server/src/service/socket.io/shared.js:68:44)
at Namespace.<anonymous> (/usr/local/lib/node_modules/p3x-redis-ui/node_modules/p3x-redis-ui-server/src/service/socket.io/socket.js:90:24)
at Namespace.emit (node:events:378:20)
at /usr/local/lib/node_modules/p3x-redis-ui/node_modules/socket.io/dist/namespace.js:134:27
at processTicksAndRejections (node:internal/process/task_queues:76:11)
socket.io connected dNmj9eh3QpZom7IKAAAB

**Comment by Frontrider** [comment]
So there's not even a "because when you were doing x, it could be caused by y", s in "because it happened because I was opening settings, it could be ... ".

**Comment by Frontrider** [comment]
> to me it looks like it is not able to saving files, but i cannot debug this. but as you can see multiple kubernetes examples are there and it works. so this error looks like in the environment you setup.

Thank you, this is the answer what I was looking for. That error message was not descriptive enough for me to start debugging it.

**Comment by Frontrider** [comment]
Found the culprit.
The crash is happening on this line, when calling ` connections.list.map`, with `list` being undefined:
https://github.com/patrikx3/redis-ui-server/blob/23154624d73002c394a5cac9bea61c23bc5a821d/src/service/socket.io/shared.js#L68

Is that the list of already declared connections (which is 100% undefined in my case as I can not connect to the cluster from outside the environment, and I'm trying to create a new one from the gui), or is it trying to send an empty connection to the server, before I was done with it?
