### ISSUE TITLE
Refreshing Browser in Cluster Mode causes "502 Bad Gateway"

### ISSUE THREAD

**Issue by jangammohan** [patrikx3/redis-ui#55]
I see there is an issue opened on this already and it is resolved in v2021.4.106 (https://github.com/patrikx3/redis-ui/issues/50)

Currently, we are using higher version 2021.4.141, looks like on this version the issue is back again, we see the same "502 Bad Gateway" error. 

do you recommend sticking with the 2014.4.106 version to not see this issue?

**Comment by jangammohan** [comment]
Currently, we create our own image by downloading version 2014.4.141 from npm. Our dockerfile has the below command 

RUN npm -g --unsafe-perm install p3x-redis-ui@2021.4.141. , we deploy created docker image on kubernetes, UI loads for the first time but after minutes or on refresh it gives see below error.

![image](https://user-images.githubusercontent.com/44169638/112686031-c4c70200-8e4b-11eb-8bdd-1e855ccf316b.png)



Error Details:

[P3XRS] [PID: 000008]  3/25/2021, 7:41:57 PM unhandledRejection ReplyError: ERR SELECT is not allowed in cluster mode
    at parseError (/usr/local/lib/node_modules/p3x-redis-ui/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/usr/local/lib/node_modules/p3x-redis-ui/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'select', args: [ '1' ] }
} Promise {
  <rejected> ReplyError: ERR SELECT is not allowed in cluster mode
      at parseError (/usr/local/lib/node_modules/p3x-redis-ui/node_modules/redis-parser/lib/parser.js:179:12)
      at parseType (/usr/local/lib/node_modules/p3x-redis-ui/node_modules/redis-parser/lib/parser.js:302:14) {
    command: { name: 'select', args: [Array] }
  }
}
